version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python main.py

workflows:
  build_and_test_deploy:
    jobs:
      - build
